-- MySQL Script generated by MySQL Workbench
-- Thu Dec 27 23:28:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TipoEsame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoEsame` (
  `IDTipoEsame` INT NOT NULL AUTO_INCREMENT,
  `Materia` VARCHAR(45) NOT NULL,
  `PuntiTot` INT NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  `PercentualeCorrette` INT NOT NULL,
  `MaxPartecipanti` INT NOT NULL,
  PRIMARY KEY (`IDTipoEsame`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sessione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sessione` (
  `IDSessione` INT NOT NULL AUTO_INCREMENT,
  `DataSessione` VARCHAR(10) NOT NULL,
  `OraInizio` VARCHAR(5) NOT NULL,
  `OraFine` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`IDSessione`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aula` (
  `IDAula` INT NOT NULL AUTO_INCREMENT,
  `NomeAula` VARCHAR(45) NOT NULL,
  `Capienza` INT NOT NULL,
  PRIMARY KEY (`IDAula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Esame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Esame` (
  `IDEsame` INT NOT NULL AUTO_INCREMENT,
  `IDSessione` INT NOT NULL,
  `IDTipoEsame` INT NOT NULL,
  `PostiLiberi` INT NOT NULL,
  `OraInizio` VARCHAR(5) NOT NULL,
  `OraFine` VARCHAR(5) NOT NULL,
  `IDAula` INT NOT NULL,
  PRIMARY KEY (`IDEsame`),
  INDEX `fk_Sessione_has_TipoEsame_TipoEsame1_idx` (`IDTipoEsame` ASC) VISIBLE,
  INDEX `fk_Sessione_has_TipoEsame_Sessione_idx` (`IDSessione` ASC) VISIBLE,
  INDEX `fk_Esame_Aula1_idx` (`IDAula` ASC) VISIBLE,
  CONSTRAINT `fk_Sessione_has_TipoEsame_Sessione`
    FOREIGN KEY (`IDSessione`)
    REFERENCES `mydb`.`Sessione` (`IDSessione`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sessione_has_TipoEsame_TipoEsame1`
    FOREIGN KEY (`IDTipoEsame`)
    REFERENCES `mydb`.`TipoEsame` (`IDTipoEsame`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Esame_Aula1`
    FOREIGN KEY (`IDAula`)
    REFERENCES `mydb`.`Aula` (`IDAula`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Esaminando`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Esaminando` (
  `CFEsaminando` VARCHAR(16) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Sesso` CHAR(1) NOT NULL,
  `DataNascita` VARCHAR(10) NOT NULL,
  `LuogoNascita` VARCHAR(45) NOT NULL,
  `BoolStudente` CHAR(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`CFEsaminando`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SkillCard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SkillCard` (
  `IDSkillCard` INT NOT NULL AUTO_INCREMENT,
  `DataEmissione` VARCHAR(10) NOT NULL,
  `DataScadenza` VARCHAR(10) NOT NULL,
  `Scaduta` CHAR(1) NOT NULL DEFAULT 0,
  `CFEsaminando` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`IDSkillCard`),
  INDEX `fk_SkillCard_Esaminando1_idx` (`CFEsaminando` ASC) VISIBLE,
  CONSTRAINT `fk_SkillCard_Esaminando1`
    FOREIGN KEY (`CFEsaminando`)
    REFERENCES `mydb`.`Esaminando` (`CFEsaminando`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Partecipazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Partecipazione` (
  `IDPartecipazione` INT NOT NULL AUTO_INCREMENT,
  `IDSkillCard` INT NOT NULL,
  `IDEsame` INT NOT NULL,
  `Esito` INT NULL,
  `Promosso` CHAR(1) NULL,
  PRIMARY KEY (`IDPartecipazione`),
  INDEX `fk_SkillCard_has_Esame_Esame1_idx` (`IDEsame` ASC) VISIBLE,
  INDEX `fk_SkillCard_has_Esame_SkillCard1_idx` (`IDSkillCard` ASC) VISIBLE,
  CONSTRAINT `fk_SkillCard_has_Esame_SkillCard1`
    FOREIGN KEY (`IDSkillCard`)
    REFERENCES `mydb`.`SkillCard` (`IDSkillCard`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SkillCard_has_Esame_Esame1`
    FOREIGN KEY (`IDEsame`)
    REFERENCES `mydb`.`Esame` (`IDEsame`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
